### ISSUE TITLE
could you provide the pretrained vector of chemdner?

### ISSUE THREAD

**Issue by jiacheng-ye** [zhijing-jin/GraphIE#2]
Hi, zhijing, thanks a lot for your codes. I saw `chemdner_pubmed_drug.word2vec_model_token4_d50` in your `multi_runs_CHEMDNER.py` file. Did you use the pretrained vector rather then glove? Could you provide the pretrained vector of chemdner?

**Comment by zhijing-jin** [comment]
Hi Jiacheng,

Thanks for the good question! This pretrained vector of chemdner is first introduced in [Ling Luo's BiLSTM Approach, 2017](https://academic.oup.com/bioinformatics/article/34/8/1381/4657076).

I used their word2vec file but unfortunately I cannot locate it as my data server has changed several times. I would refer you to Luo's implementation, and someone has mentioned the same [data path question](https://github.com/lingluodlut/Att-ChemdNER/issues/2) to the author before.

Technically, they downloaded a total of 1 918 662 MEDLINE abstracts from the PubMed website with the query string ‘chemical’. Then these abstracts and CHEMDNER corpus were used to train
word embedding by the word2vec tool using the skip-gram model as pre-trained word embedding.

That might explain the reason why this pretrained word2vec is better than GLOVE for this task.

**Comment by jiacheng-ye** [comment]
Thanks for your detailed explanation~
